const expressEdge = require('express-edge')
const express = require('express')
const mongoose = require('mongoose')
const bodyParser = require('body-parser')
const app = new express()
const fileUpload = require('express-fileupload')
const createPostController = require('./controllers/createPost')
const homePageController = require('./controllers/homePage')
const storePostController = require('./controllers/storePost')
const getPostController= require('./controllers/getPost')
const updatePostController=require('./controllers/updatePost')
const deletePostController = require('./controllers/deletePost')
const createUserController = require('./controllers/createUser')
const storeUserController = require('./controllers/storeUser')
const loginController=require('./controllers/login')
const loginUserController=require('./controllers/loginUser')
mongoose.connect('mongodb://localhost/lost-found')

//middleware
app.use(express.static('public'))
app.use(expressEdge)
app.set('views' ,`${__dirname}/views`)
app.use(fileUpload())
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({extended:true}))
const storePost = require('./middleware/storePost')
app.use('/posts/store',storePost)

//url management
app.get('/',homePageController)
app.post('/posts/store',storePostController)
app.get('/posts/delete/:id',deletePostController)
app.post('/posts/update/:id',updatePostController)
app.get('/post/:id',getPostController)
app.get('/posts/new',createPostController)
app.post('/user/login',loginUserController)
app.get('/auth/register',createUserController)
app.post('/auth/store',storeUserController)
app.get('/auth/login',loginController)

app.listen(4000,()=>{
    console.log("start listening!")
})